INSERT INTO inventory (name, type_of_game, available) VALUES ('age of empires', 'CLASSIC', false);
INSERT INTO inventory (name, type_of_game) VALUES ('tekken 9', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('tomb raider', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('lemmings', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('fifa 2021', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('Day of Defeat', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('League of legends', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('age of empires', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('Command&Conquer', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('age of empires', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('tekken 9', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('tomb raider', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('lemmings', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('fifa 2021', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('Day of Defeat', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('League of legends', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('age of empires', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('Command&Conquer', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('age of empires', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('tekken 9', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('tomb raider', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('lemmings', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('fifa 2021', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('Day of Defeat', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('League of legends', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('age of empires', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('Command&Conquer', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('age of empires', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('tekken 9', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('tomb raider', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('lemmings', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('fifa 2021', 'NEW_RELEASE');
INSERT INTO inventory (name, type_of_game) VALUES ('Day of Defeat', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('League of legends', 'STANDARD');
INSERT INTO inventory (name, type_of_game) VALUES ('age of empires', 'CLASSIC');
INSERT INTO inventory (name, type_of_game) VALUES ('Command&Conquer', 'CLASSIC');
INSERT INTO customers (name, last_name, mail) VALUES ('Marcos', 'Aguirre Miñarro', 'maguirreminarro@gmail.com');